# Generated by Django 3.1.4 on 2021-06-29 12:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0003_auto_20210223_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='completed_days',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='elapsed_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='expected_days',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='use_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 12, 12, 47, 417524, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WaitingEscalate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalated_date', models.DateField()),
                ('reason', models.CharField(max_length=700)),
                ('agent_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.team')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.supervisor')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='supervisor',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.profile'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.team'),
        ),
        migrations.CreateModel(
            name='HistoricalTicket',
            fields=[
                ('id', models.CharField(db_index=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('ticket_date', models.DateField()),
                ('ticket_time', models.TimeField()),
                ('use_date', models.DateTimeField()),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('expected_days', models.DurationField(blank=True, null=True)),
                ('escalated', models.CharField(choices=[('Escalate', 'Escalate')], max_length=60)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('completed_days', models.DurationField(blank=True, null=True)),
                ('elapsed_time', models.DurationField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='helpdesk.technician')),
                ('agent_team', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='helpdesk.team')),
                ('astatus', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='helpdesk.agent_status')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='helpdesk.category')),
                ('district', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='helpdesk.district')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='helpdesk.profile')),
                ('prority', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='helpdesk.prority')),
                ('region', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='helpdesk.region')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='helpdesk.status')),
            ],
            options={
                'verbose_name': 'historical ticket',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
