# Generated by Django 3.1.4 on 2021-07-22 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210723_0040'),
        ('helpdesk', '0004_auto_20210629_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='session',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.AlterField(
            model_name='assignedticket',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.profile'),
        ),
        migrations.AlterField(
            model_name='escalatedticket',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.profile'),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='district',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.district'),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.profile'),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='region',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.region'),
        ),
        migrations.AlterField(
            model_name='history',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.profile'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.profile'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.profile'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.district'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.profile'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.region'),
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
