# Generated by Django 3.1.4 on 2021-07-22 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalteam',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltechnician',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltechnician',
            name='team',
        ),
        migrations.RemoveField(
            model_name='historicaltechnician',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='team',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='team',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='technician',
        ),
        migrations.DeleteModel(
            name='HistoricalHod',
        ),
        migrations.DeleteModel(
            name='HistoricalTeam',
        ),
        migrations.DeleteModel(
            name='HistoricalTechnician',
        ),
        migrations.DeleteModel(
            name='Hod',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Technician',
        ),
    ]
