# Generated by Django 3.1.4 on 2021-07-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210723_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequisition_details',
            name='detail_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='requisition_details',
            name='detail_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
