# Generated by Django 3.1.4 on 2021-07-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210723_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljob_specification',
            name='control',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='job_specification',
            name='control',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending')], default='Pending', max_length=30),
        ),
    ]
