# Generated by Django 3.1.4 on 2021-07-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210725_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalprofile',
            name='is_helpdesk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalprofile',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_helpdesk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
