# Generated by Django 3.1.4 on 2021-08-02 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_historicalsupervisor_historicalunit_link_supervisor_unit_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequisition',
            name='unit_head',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.supervisor'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='unit_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.supervisor'),
        ),
    ]
