# Generated by Django 3.1.4 on 2021-08-03 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_historicalinventory_stock_record_inventory_stock_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventory_stock_record',
            name='issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalinventory_stock_record',
            name='issued_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.profile'),
        ),
        migrations.AddField(
            model_name='inventory_stock_record',
            name='issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory_stock_record',
            name='issued_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.profile'),
        ),
    ]
