# Generated by Django 3.1.4 on 2021-08-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20210803_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequisition_details',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisition_details',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
