# Generated by Django 3.1.4 on 2021-08-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20210803_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequisition',
            name='check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisition',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
