# Generated by Django 3.1.4 on 2021-08-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20210803_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljob_specification',
            name='check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job_specification',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
